# Generated by Django 2.2.11 on 2020-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Status', models.IntegerField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
    ]
