# Generated by Django 2.2.11 on 2020-03-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=15)),
                ('RollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=40)),
                ('RegistrationDate', models.CharField(max_length=40)),
                ('Class', models.CharField(max_length=40, null=True)),
                ('Gender', models.CharField(max_length=10)),
                ('MobileNo', models.IntegerField()),
                ('ParentsName', models.CharField(max_length=40)),
                ('ParentMobileNo', models.IntegerField()),
                ('BirthDate', models.CharField(max_length=20)),
                ('BloodGroup', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=40)),
            ],
        ),
    ]
